language: go
sudo: false
go:
  - "1.8"
  - "1.9"
  - "1.10"
before_install:
  - go get github.com/mattn/goveralls
script:
  - $GOPATH/bin/goveralls -service=travis-ci -race -package github.com/romangrechin/cmd -show
